### ISSUE TITLE
OnLogin exception

### ISSUE THREAD

**Issue by Bloodlex** [woutzah/ChatBrawl#1]
Hey, I've encountered this after login:

[https://pastebin.com/2pjpEgDU](https://pastebin.com/2pjpEgDU)

**Comment by wouter-blockken** [comment]
Hey there,

It looks like it's complaining about the scramblerace start announce message, can you double check if you didn't leave it empty/removed it for me?

**Comment by Bloodlex** [comment]
> Hey there,
> 
> It looks like it's complaining about the scramblerace start announce message, can you double check if you didn't leave it empty/removed it for me?

Hm, that's odd. Everything seems to work except for that that sometimes I get such exceptions like this. Here is my Scramblerace config:

[https://pastebin.com/NLGQjPb8](https://pastebin.com/NLGQjPb8)

**Comment by wouter-blockken** [comment]
I found the bug that's causing the issue, fixed it and will be released on next update. Thanks for reporting!
Here is my ChatBrawl roadmap, just to see what you can expect in future updates etc. https://trello.com/b/1onUT10O/chatbrawl-roadmap
