### ISSUE TITLE
Errors in Console

### ISSUE THREAD

**Issue by SavagePanda116** [woutzah/ChatBrawl#3]
Hello, I finally just updated all of my config files to have the plugin enable again since it's latest update, but I'm receiving a few errors.

This error occurs when I use '/chatbrawl reload' to update the config files. I displays 8 times: [ChatBrawl Config Error] the commandlist for a reward is missing in the config!

This error occurs when a Chat Brawl race ends: https://pastebin.com/CLC2Ff84

This error occurs when I try to use '/chatbrawl start <race>': https://pastebin.com/gjjx4jay

-----
This is one of my race files: https://pastebin.com/8G71t52W
This is my config file: https://pastebin.com/aWGhqwYn

My server is 1.16.3 PaperSpigot build #194.
I'm using Chat Brawl version 1.7.1.

Thanks in advance!

**Comment by SavagePanda116** [comment]
Another error, this one was during the Hunt Race. It should have been the first to kill 20 Skeletons, but I killed 80 and it didn't count. This is the error: https://pastebin.com/0wMMTkpj

**Comment by SavagePanda116** [comment]
It's actually happening with every race... here is the Block Race error: https://pastebin.com/ZLukN7Lk

**Comment by wouter-blockken** [comment]
Oh i see what's wrong you forgot to add '' after the subtitle entries in the rewardssection, make sure to add those or all races will not work properly, let me know if that fixed it for you!

**Comment by SavagePanda116** [comment]
I made the changes and it's still doing the same thing :(

**Comment by wouter-blockken** [comment]
Did you do it in all your race files?

**Comment by SavagePanda116** [comment]
Yes I did, they each look like this: https://pastebin.com/wp5xH5Bj ... Am I still missing something?

**Comment by wouter-blockken** [comment]
Issue is resolved in recode of the plugin
